---
name: DAO (Statistical Intelligence)
version: 0.5.1
slug: dao_enhanced
description: Complete DAO with Statistical Intelligence, Weather Reactive, and 7-day planning
url: https://github.com/miclnl/day-ahead
arch:
  - aarch64
  - amd64
init: false
startup: application
ingress: true
ingress_port: 5001
panel_admin: false
panel_icon: mdi:lightning-bolt
apparmor: true
map:
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw
homeassistant_api: true
ports:
  5001/tcp: 5001
# Image wordt lokaal gebouwd via Dockerfile
# image: "ghcr.io/miclnl/dao-modern-{arch}"

# Basic addon configuration - energy settings configured in webapp
options:
  database_engine: sqlite
  log_level: info
  homeassistant_token: ""
  optimization_mode: "statistical" # statistical intelligence only
  cloud_ai_enabled: false # optional cloud AI (OpenAI/Anthropic)
schema:
  database_engine: list(sqlite|mysql|postgresql)
  log_level: list(debug|info|warning|error)
  homeassistant_token: password?
  homeassistant_url: str?
  optimization_mode: list(statistical)
  cloud_ai_enabled: bool
