---
name: DAO+
version: 2025.8.0
slug: day_aheadplus_opt
description: Home Assistant Community Add-ons for day ahead optimizations
url: https://github.com/miclnl/day-ahead
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 5000
panel_admin: false
panel_icon: mdi:home-battery-outline
apparmor: true
legacy: true
map:
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw
homeassistant_api: true
ports:
  5000/tcp: 5000
