---
name: 🪶 DAO Light (Minimal & Stable)
version: 1.0.0
slug: dao_light_minimal
description: Lightweight and stable DAO with minimal dependencies for reliable operation on Pi
url: https://github.com/miclnl/day-ahead
codenotary: cees.van.beek@xs4all.nl
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8099
panel_admin: false
panel_icon: mdi:feather
apparmor: true
legacy: true
map:
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw
homeassistant_api: true
ports:
  5002/tcp: 5002
# Image wordt lokaal gebouwd via Dockerfile
# image: "ghcr.io/miclnl/dao-light-{arch}"

# Simplified configuration schema for Light version
options:
  database_engine: sqlite
  log_level: info
  optimization_interval: 60
schema:
  database_engine: list(sqlite|mysql)
  log_level: list(debug|info|warning|error)
  optimization_interval: int(30,3600)
  homeassistant_token: password?
  energy_tax_rate: float(0.0,1.0)?
  battery_capacity: float(0.0,100.0)?
