---
name: 🪶 DAO Light (Minimal & Stable)
version: 1.1.2
slug: dao_light_minimal
description: Lightweight and stable DAO with minimal dependencies for reliable operation on Pi
url: https://github.com/miclnl/day-ahead
codenotary: cees.van.beek@xs4all.nl
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8099
panel_admin: false
panel_icon: mdi:feather
apparmor: true
legacy: true
map:
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw
homeassistant_api: true
ports:
  5002/tcp: 5002
# Image wordt lokaal gebouwd via Dockerfile
# image: "ghcr.io/miclnl/dao-light-{arch}"

# Basic addon configuration - energy settings configured in webapp
options:
  database_engine: sqlite
  log_level: info
  homeassistant_token: ""
schema:
  database_engine: list(sqlite|mysql)
  log_level: list(debug|info|warning|error)
  homeassistant_token: password?
